import: comunica/travis-presets:yarn-monorepo.yml@master
script:
  - lerna run integration --concurrency 1
deploy:
  - provider: script
    skip-cleanup: true
    script: ./web-clients/build-web-clients.sh && ./web-clients/deploy-web-clients.sh
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
